main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'main/main.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza


# Create your views here.

def index(request):
    ''' pizzas = Pizza.objects.all()
    pizzas_name_and_price = [pizza.nom + " : " + str(pizza.prix) + " $" for pizza in pizzas]
    pizzas_str_and_price = ", ".join(pizzas_name_and_price)
    return HttpResponse("Les Pizza: " + pizzas_str_and_price)'''
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

main/templates/main/main.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>PRINCIPAL</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centred">
        <img src="{% static 'main/images/main_logo.png' %}">
        <br>
        <a href="{% url 'menu:index' %}">Voir Le Menu</a>
    </div>
</body>
</html>

menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
<body>
    <a href="{% url 'main:index' %}"><img class="img-logo" src="{% static 'menu/images/small_logo.png' %}"></a>
    <div class="menu-h1">
        <h1>Les Pizzas</h1>
    </div>
    <div class="menu-list">
            {% for pizza in pizzas %}
            <div class="nom-pizza">
                <span class="li-pizza">{{pizza.nom }}</span>
                <span class="li-pizza-p"> {{ pizza.prix | floatformat:2}} € </span>
                <span class="li-pizza-ing">{{pizza.ingredients}} </span>
                {% if pizza.vegetarienne %}
                    <span class="veg"> VEGETARIENNE </span>
                {% endif %}
            </div>
            {% endfor %}
    </div>
</body>
</html>